/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopsNewRouteImport } from './routes/shops.new'
import { Route as ShopsShopIdRouteImport } from './routes/shops.$shopId'
import { Route as ShopsShopIdEditRouteImport } from './routes/shops.$shopId.edit'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsNewRoute = ShopsNewRouteImport.update({
  id: '/shops/new',
  path: '/shops/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdRoute = ShopsShopIdRouteImport.update({
  id: '/shops/$shopId',
  path: '/shops/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdEditRoute = ShopsShopIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ShopsShopIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/shops/$shopId': typeof ShopsShopIdRouteWithChildren
  '/shops/new': typeof ShopsNewRoute
  '/shops/$shopId/edit': typeof ShopsShopIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/shops/$shopId': typeof ShopsShopIdRouteWithChildren
  '/shops/new': typeof ShopsNewRoute
  '/shops/$shopId/edit': typeof ShopsShopIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/shops/$shopId': typeof ShopsShopIdRouteWithChildren
  '/shops/new': typeof ShopsNewRoute
  '/shops/$shopId/edit': typeof ShopsShopIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/login'
    | '/profile'
    | '/shops/$shopId'
    | '/shops/new'
    | '/shops/$shopId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/login'
    | '/profile'
    | '/shops/$shopId'
    | '/shops/new'
    | '/shops/$shopId/edit'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/login'
    | '/profile'
    | '/shops/$shopId'
    | '/shops/new'
    | '/shops/$shopId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ShopsShopIdRoute: typeof ShopsShopIdRouteWithChildren
  ShopsNewRoute: typeof ShopsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/new': {
      id: '/shops/new'
      path: '/shops/new'
      fullPath: '/shops/new'
      preLoaderRoute: typeof ShopsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId': {
      id: '/shops/$shopId'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof ShopsShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId/edit': {
      id: '/shops/$shopId/edit'
      path: '/edit'
      fullPath: '/shops/$shopId/edit'
      preLoaderRoute: typeof ShopsShopIdEditRouteImport
      parentRoute: typeof ShopsShopIdRoute
    }
  }
}

interface ShopsShopIdRouteChildren {
  ShopsShopIdEditRoute: typeof ShopsShopIdEditRoute
}

const ShopsShopIdRouteChildren: ShopsShopIdRouteChildren = {
  ShopsShopIdEditRoute: ShopsShopIdEditRoute,
}

const ShopsShopIdRouteWithChildren = ShopsShopIdRoute._addFileChildren(
  ShopsShopIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ShopsShopIdRoute: ShopsShopIdRouteWithChildren,
  ShopsNewRoute: ShopsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
